---
title: "Typical-values-lobes"
author: "Fernanda Hansen P. de Moraes"
date: "28/09/2021"
output: 
  html_document: 
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message=FALSE)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(cache=TRUE)
```

```{r, message=FALSE, warning=FALSE, include=FALSE}
setwd("~/GitHub/Typical-values")

set.seed(1)
```

```{r packages, message=FALSE, warning=FALSE, include=FALSE}
library(plyr);
library(dplyr);
library(stringi);
library(tidyverse);
library(readxl);
library(modelr);
library(ggpubr);
library(readr);
library(kableExtra);
library(broom);
library(arm);
library(MuMIn);
library(lme4);
library(lsmeans);
library(effects);
```

```{r data import}
data <- read_csv("~/GitHub/Typical-values/data_typical_values.csv")
```


```{r data prep}
Age.cor = 25

data <- data %>%
  mutate(
  logAvgThickness = log10(AvgThickness),
  logTotalArea = log10(TotalArea),
  logExposedArea = log10(ExposedArea),
  localGI = TotalArea/ExposedArea,
  k = sqrt(AvgThickness) * TotalArea/(ExposedArea ^ 1.25),
  K = 1/4 * log10(AvgThickness^2)+log10(TotalArea) - 5/4 * log10(ExposedArea),
  S = 3/2 * log10(TotalArea) + 3/4 * log10(ExposedArea) - 9/4 * log10(AvgThickness^2) ,
  I = log10(TotalArea) + log10(ExposedArea) + log10(AvgThickness^2) ,
  Knorm = K/sqrt(1 + (1/4)^2 + (5/4)^2),
  Snorm = S/sqrt((3/2)^2 + (3/4)^2 + (9/4)^2),
  Inorm = I/sqrt(1^2 + 1^2 + 1^2),
  TotalArea_corrected = ifelse(ROI == "hemisphere", TotalArea, TotalArea * c),
  ExposedArea_corrected = ifelse(ROI == "hemisphere", ExposedArea, ExposedArea * c),
  logTotalArea_corrected = log10(TotalArea_corrected),
  logExposedArea_corrected = log10(ExposedArea_corrected),
  localGI_corrected = ifelse(
    ROI == "hemisphere",
    TotalArea/ExposedArea,
    TotalArea_corrected/ExposedArea_corrected
  ),
  k_corrected = ifelse(
    ROI == "hemisphere",
    sqrt(AvgThickness) * log10(TotalArea)/(log10(ExposedArea) ^ 1.25),
    sqrt(AvgThickness) * log10(TotalArea_corrected)/(log10(ExposedArea_corrected^1.25) )
  ),
  K_corrected =  ifelse(
    ROI == "hemisphere",
    1/4 * log10(AvgThickness^2)+ log10(TotalArea) - 5/4 * log10(ExposedArea),
    1/4 * log10(AvgThickness^2) + log10(TotalArea_corrected) - 5/4 * log10(ExposedArea_corrected)
  ),
  I_corrected = ifelse(
    ROI == "hemisphere",
    log10(TotalArea) + log10(ExposedArea) + log10(AvgThickness^2) ,
    log10(TotalArea_corrected) + log10(ExposedArea_corrected) + log10(AvgThickness^2) 
  ),
  S_corrected = ifelse(
    ROI == "hemisphere",
    3/2 * log10(TotalArea) + 3/4 * log10(ExposedArea) - 9/4 * log10(AvgThickness^2) ,
    3/2 * log10(TotalArea_corrected) + 3/4 * log10(ExposedArea_corrected) - 9/4 * log10(AvgThickness^2) 
  )
)

```

```{r age intervals}
data$Age_interval <- cut(data$Age,
                                       breaks = c(0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100),
                                       right = FALSE,
                                       include.lowest = TRUE)

data$Age_interval10 <- cut(data$Age,
                                       breaks = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100),
                                       right = FALSE,
                                       include.lowest = TRUE)
```

# Datasets description

We included multiple datasets from different sites to estimate, accounting methodological and "subject" biases, typical values for K, S and I.

```{r description, echo=FALSE}
filter(data, ROI != "hemisphere") %>%
  group_by(Diagnostic) %>%
  summarise(
    N = n_distinct(SUBJ),
    age = paste(signif(mean(Age), 2), "±", signif(sd(Age), 2)),
    age_range = paste(signif(min(Age), 2), "; ", signif(max(Age), 2))
) %>% kable(digits = 2) %>% kable_styling()

filter(data, ROI != "hemisphere") %>%
  group_by(Diagnostic, Gender) %>%
  summarise(
    N = n_distinct(SUBJ)
) %>% kable(digits = 2) %>% kable_styling()

filter(data, ROI != "hemisphere") %>%
  summarise(
    N = n_distinct(SUBJ),
    age = paste(signif(mean(Age), 2), "±", signif(sd(Age), 2)),
    age_range = paste(signif(min(Age), 2), "; ", signif(max(Age), 2))
) %>% kable(digits = 2) %>% kable_styling()

filter(data,
       ROI != "hemisphere") %>%
  group_by(Sample, Diagnostic, ROI) %>%
  summarise(
    N = n_distinct(SUBJ),
    age = paste(signif(mean(Age), 2), "±", signif(sd(Age), 2)),
    age_range = paste(signif(min(Age), 2), "; ", signif(max(Age), 2)),
    AvgT =  paste(signif(mean(AvgThickness), 2), "±", signif(sd(AvgThickness), 2)),
    AT =  paste(signif(mean(TotalArea), 2), "±", signif(sd(TotalArea), 2)),
    AE =  paste(signif(mean(ExposedArea), 2), "±", signif(sd(ExposedArea), 2)),
    K =  paste(signif(mean(K), 2), "±", signif(sd(K), 2)),
    S =  paste(signif(mean(S), 2), "±", signif(sd(S), 2)),
    I =  paste(signif(mean(I), 2), "±", signif(sd(I), 2))
  ) %>% kable(digits = 2) %>% kable_styling()

filter(data, ROI != "hemisphere") %>%
  group_by(Sample, Diagnostic, Gender) %>%
  summarise(
    N = n_distinct(SUBJ)
) %>% kable(digits = 2) %>% kable_styling()
```

```{r echo=FALSE}
data_lobes <- filter(data, ROI != "hemisphere", Diagnostic == "CTL" | Diagnostic == "MCI"| Diagnostic == "AD")
data_lobes$Diagnostic <- factor(data_lobes$Diagnostic, levels = c("CTL", "MCI","AD"))
data_lobes$Sample <- as.factor(data_lobes$Sample)

N_SUBJ <- data_lobes %>% group_by(Diagnostic, ROI) %>% summarise(N_SUBJ = n_distinct(SUBJ))
```

# Mapping

## CTL

```{r}
amostra_Coef <- filter(data_lobes, Diagnostic == "CTL", Age_interval != "[0,5)", Age_interval != "[95,100]") %>%
    group_by(Age_interval, ROI) %>%
    do(fit_amostra = tidy(lm(1/2 * logAvgThickness + logTotalArea_corrected ~ logExposedArea_corrected, data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
    unnest(fit_amostra)

amostras_Coef_age <- filter(data_lobes, Diagnostic == "CTL", Age_interval != "[0,5)", Age_interval != "[95,100]") %>%
    group_by(Age_interval) %>%
    summarise(
        N = n_distinct(SUBJ),
        min_age = min(Age),
        max_age = max(Age))

amostra_Coef <- full_join(amostra_Coef, amostras_Coef_age) %>% filter(term == "logExposedArea_corrected")

ggplot(amostra_Coef, aes(y = estimate, x = Age_interval)) +
    geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
    geom_point() +
  geom_hline(yintercept = 1.25, linetype = "dashed") +
    theme_pubr() + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9)) +
  labs(y ="Slope", x = "Age interval") +
  geom_text(aes(label = N), nudge_y = 0.3) +
  facet_grid(ROI ~ .)

amostra_Coef %>%
  dplyr::select(-c(term)) %>%
  kable() %>%
  kable_styling()

ggplot(filter(data_lobes, Diagnostic == "CTL", Age_interval != "[0,5)", Age_interval != "[95,100]"), aes(y = K, x = Age_interval), aes(y = K, x = Age_interval)) +
    geom_boxplot() + 
    theme_pubr() + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9)) +
  facet_grid(ROI ~ .)

```

### per subject
```{r}
amostra_Coef <- filter(data_lobes, Diagnostic == "CTL", Age_interval != "[0,5)", Age_interval != "[95,100]") %>%
    group_by(SUBJ) %>%
    do(fit_amostra = tidy(lm(1/2 * logAvgThickness + logTotalArea_corrected ~ logExposedArea_corrected, data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
    unnest(fit_amostra)

ggplot(filter(amostra_Coef, term == "logExposedArea_corrected"), aes(x = estimate, alpha = 0.3)) +
    geom_histogram() +
  geom_vline(xintercept = 1.25, linetype = "dashed") +
    theme_pubr() + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9)) +
  labs(x ="Slope", x = "Age interval")
```


```{r mapping}
paste("Total number of CTL subjects =", n_distinct(filter(data, ROI == "hemisphere", Diagnostic == "CTL")$SUBJ))
paste("Age range CTL. Min age = ", min(filter(data, ROI == "hemisphere", Diagnostic == "CTL")$Age), "; max age = ", max(filter(data, ROI == "hemisphere", Diagnostic == "CTL")$Age))

ggplot(filter(data, ROI == "hemisphere", Diagnostic == "CTL"),
       aes(x = Age , y = K)) +
  geom_point(aes(color = Sample, fill = Sample, alpha = 0.4)) +
  geom_smooth(color = "black", method = "lm") +
  theme_pubr() +
  guides(alpha = "none")+ 
  labs(x = "Age [years]") +
  facet_grid(ROI~.)

filter(data_lobes, Diagnostic == "CTL") %>%
  group_by(ROI) %>%
  summarize(COR=cor(K, Age),
            p = cor.test(K, Age)$p.value)

ggplot(filter(data, ROI == "hemisphere", Diagnostic == "CTL"),
       aes(x = Age, y = S)) +
  geom_point(aes(color = Sample, fill = Sample, alpha = 0.4)) +
  geom_smooth(color = "black", method = "lm") +
  theme_pubr() +
  guides(alpha = "none", color = "none",fill = "none")+ 
  labs(x = "Age [years]") +
  theme(legend.position= "none") +
  facet_grid(ROI~.)

filter(data_lobes, Diagnostic == "CTL") %>%
  group_by(ROI) %>%
  summarize(COR=cor(S, Age),
            p = cor.test(S, Age)$p.value)

ggplot(filter(data, ROI == "hemisphere", Diagnostic == "CTL"),
             aes(x = Age, y = I)) +
  geom_point(aes(color = Sample, fill = Sample, alpha = 0.4)) + 
  geom_smooth(color = "black", method = "lm") +
  theme_pubr() +
  guides(alpha = "none", color = "none",fill = "none") + 
  labs(x = "Age [years]") +
  theme(legend.position= "none") +
  facet_grid(ROI~.)

filter(data_lobes, Diagnostic == "CTL") %>%
  group_by(ROI) %>%
  summarize(COR=cor(I, Age),
            p = cor.test(I, Age)$p.value)
```

## CTL vs AD

```{r}
amostra_Coef <- filter(data_lobes, Diagnostic == "CTL" | Diagnostic == "AD", Age_interval != "[0,5)", Age_interval != "[95,100]") %>%
    group_by(Age_interval, Diagnostic) %>%
    do(fit_amostra = tidy(lm(1/2 * logAvgThickness + logTotalArea ~ logExposedArea, data = ., na.action = na.omit), conf.int = TRUE, conf.level = 0.95)) %>% 
    unnest(fit_amostra)

amostras_Coef_age <- filter(data_lobes, Diagnostic == "CTL" | Diagnostic == "AD", Age_interval != "[0,5)", Age_interval != "[95,100]") %>%
    group_by(Age_interval, Diagnostic) %>%
    summarise(
        N = n_distinct(SUBJ),
        min_age = min(Age),
        max_age = max(Age))

amostra_Coef <- full_join(amostra_Coef, amostras_Coef_age) %>%
  filter(term == "logExposedArea")

amostra_Coef$Diagnostic <- factor(amostra_Coef$Diagnostic, levels=c('AD', 'CTL'))

ggplot(amostra_Coef, aes(y = estimate, x = Age_interval, color = Diagnostic)) +
    geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
    geom_point() +
  geom_hline(yintercept = 1.25, linetype = "dashed") +
    theme_pubr() + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9)
    ) +
  labs(y ="Slope", x = "Age interval") +
  geom_text(aes(label = N), nudge_y = 0.3) +
  facet_grid(ROI ~ .)

amostra_Coef %>%
  dplyr::select(-c(term)) %>%
  kable() %>%
  kable_styling()

```



# LOBES

### AvgThickness \~ Age

```{r echo=FALSE}
m.1 <- lme4::lmer(AvgThickness ~ Age * Diagnostic * ROI + (1|Sample) + (1|Sample:Diagnostic) + (1|Sample:ROI), data = data_lobes)

anova(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

mean <- lsmeans(m.1, ~ Diagnostic*ROI, var="Age")
m.lstk <- lstrends(m.1, ~ Diagnostic*ROI, var="Age")
pairs <- pairs(m.lstk) 

mean <- as_tibble(mean)
m.lstk <- as_tibble(m.lstk)

lst <- m.lstk %>% mutate(
    TX = paste(signif(Age.trend, 2), "±", signif(SE, 2)))

tableT <- full_join(mean, lst, by = c("Diagnostic", "ROI")) %>% mutate(percent = Age.trend*100/abs(lsmean), Variable = "T")

pairs <- as_tibble(pairs) %>%
  mutate(Contrast.1 = str_split(contrast, pattern = " - ", simplify = TRUE)[,1], Contrast.2 = str_split(contrast, pattern = " - ", simplify = TRUE)[,2]) %>%
  mutate(Diagnostic.1 = str_split(Contrast.1, pattern = " ", simplify = TRUE)[,1], ROI.1 = str_split(Contrast.1, pattern = " ", simplify = TRUE)[,2], Diagnostic.2 = str_split(Contrast.2, pattern = " ", simplify = TRUE)[,1], ROI.2 = str_split(Contrast.2, pattern = " ", simplify = TRUE)[,2]) %>%
  mutate(contrast = str_c(Diagnostic.1, Diagnostic.2 ,sep = "-"), contrast_ROI = str_c(ROI.1, ROI.2 ,sep = "-"))

coefs <- data.frame(coef(summary(m.1)))
coefs$p.z <- 2 * (1 - pnorm(abs(coefs$t.value)))
coefs

## Within regions comparison

ggplot(data = filter(pairs, ROI.1 == ROI.2), aes(
    x = contrast,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.4, nudge_y = 0.0003) +
  facet_wrap(ROI.1 ~.) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'AvgThickness/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))

## Within diagnostics 

ggplot(data = filter(pairs, Diagnostic.1 == Diagnostic.2), aes(
    x = contrast_ROI,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.4, nudge_y = 0.0003) +
  facet_wrap(Diagnostic.1 ~.) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'AvgThickness/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))

e <- effect("Age:Diagnostic:ROI", m.1)
e <- as.data.frame(e)

ggplot(e, aes(x = Age, y = fit,ymin=lower, ymax=upper, shape = Diagnostic)) + geom_pointrange() + geom_line() + theme_pubr() + labs(x = "Age [years]", y = "AvgThickness", shape = "Diagnostic") + facet_wrap(. ~ ROI)

re <- as_tibble(ranef(m.1))

re <- filter(re, grpvar == "Sample:ROI") %>%
  mutate(ROI = str_sub(grp, -1, 20), T_shift = condval, Sample = str_split(grp, pattern = ":", simplify = TRUE)[,1], Diagnostic = str_split(grp, pattern = ":", simplify = TRUE)[,2], SD_T_shift = condsd) %>%
  dplyr::select(-c(condval, grpvar, term, condsd, grp))

ggplot(re, aes(y = T_shift, x = Sample)) +
  geom_point() +
  geom_errorbar(aes(ymin = T_shift+1.96*SD_T_shift, ymax = T_shift-1.96*SD_T_shift), width = 0.2) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  theme_pubr() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9)
  ) +
  labs(y ="T variation", x = "Sample") +
  facet_grid(ROI ~. )

```

### GI \~ Age

```{r echo=FALSE}
m.1 <- lme4::lmer(localGI ~ Age * Diagnostic * ROI + (1|Sample) + (1|Sample:Diagnostic) + (1|Sample:ROI), data = data_lobes)

anova(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

mean <- lsmeans(m.1, ~ Diagnostic*ROI, var="Age")
m.lstk <- lstrends(m.1, ~ Diagnostic*ROI, var="Age")
pairs <- pairs(m.lstk) 

mean <- as_tibble(mean)
m.lstk <- as_tibble(m.lstk)

lst <- m.lstk %>% mutate(
    TX = paste(signif(Age.trend, 2), "±", signif(SE, 2)))

tableT <- full_join(mean, lst, by = c("Diagnostic", "ROI")) %>% mutate(percent = Age.trend*100/abs(lsmean), Variable = "GI")

pairs <- as_tibble(pairs) %>%
  mutate(Contrast.1 = str_split(contrast, pattern = " - ", simplify = TRUE)[,1], Contrast.2 = str_split(contrast, pattern = " - ", simplify = TRUE)[,2]) %>%
  mutate(Diagnostic.1 = str_split(Contrast.1, pattern = " ", simplify = TRUE)[,1], ROI.1 = str_split(Contrast.1, pattern = " ", simplify = TRUE)[,2], Diagnostic.2 = str_split(Contrast.2, pattern = " ", simplify = TRUE)[,1], ROI.2 = str_split(Contrast.2, pattern = " ", simplify = TRUE)[,2]) %>%
  mutate(contrast = str_c(Diagnostic.1, Diagnostic.2 ,sep = "-"), contrast_ROI = str_c(ROI.1, ROI.2 ,sep = "-"))

coefs <- data.frame(coef(summary(m.1)))
coefs$p.z <- 2 * (1 - pnorm(abs(coefs$t.value)))
coefs

## Within regions comparison

ggplot(data = filter(pairs, ROI.1 == ROI.2), aes(
    x = contrast,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.4, nudge_y = 0.0003) +
  facet_wrap(ROI.1 ~.) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'GI/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))

## Within diagnostics 

ggplot(data = filter(pairs, Diagnostic.1 == Diagnostic.2), aes(
    x = contrast_ROI,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.4, nudge_y = 0.0003) +
  facet_wrap(Diagnostic.1 ~.) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'GI/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))

e <- effect("Age:Diagnostic:ROI", m.1)
e <- as.data.frame(e)

ggplot(e, aes(x = Age, y = fit,ymin=lower, ymax=upper, shape = Diagnostic)) + geom_pointrange() + geom_line() + theme_pubr() + labs(x = "Age [years]", y = "GI", shape = "Diagnostic") + facet_wrap(. ~ ROI) 

re <- as_tibble(ranef(m.1))

re <- filter(re, grpvar == "Sample:ROI") %>%
  mutate(ROI = str_sub(grp, -1, 20), GI_shift = condval, Sample = str_split(grp, pattern = ":", simplify = TRUE)[,1], Diagnostic = str_split(grp, pattern = ":", simplify = TRUE)[,2], SD_GI_shift = condsd) %>%
  dplyr::select(-c(condval, grpvar, term, condsd, grp))

ggplot(re, aes(y = GI_shift, x = Sample)) +
  geom_point() +
  geom_errorbar(aes(ymin = GI_shift+1.96*SD_GI_shift, ymax = GI_shift-1.96*SD_GI_shift), width = 0.2) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  theme_pubr() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9)
  ) +
  labs(y ="GI variation", x = "Sample") +
  facet_grid(ROI ~. )

```

### K \~ Age
```{r echo=FALSE}
m.1 <- lme4::lmer(K ~ Age * Diagnostic * ROI + (1|Sample) + (1|Sample:Diagnostic) + (1|Sample:ROI), data = data_lobes)

anova(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

mean <- lsmeans(m.1, ~ Diagnostic*ROI, var="Age")
m.lstk <- lstrends(m.1, ~ Diagnostic*ROI, var="Age")
pairs <- pairs(m.lstk) 

mean <- as_tibble(mean)
m.lstk <- as_tibble(m.lstk)

lst <- m.lstk %>% mutate(
    TX = paste(signif(Age.trend, 2), "±", signif(SE, 2)))

tableK <- full_join(mean, lst, by = c("Diagnostic", "ROI")) %>% mutate(percent = Age.trend*100/abs(lsmean), Variable = "K")

pairs <- as_tibble(pairs) %>%
  mutate(Contrast.1 = str_split(contrast, pattern = " - ", simplify = TRUE)[,1], Contrast.2 = str_split(contrast, pattern = " - ", simplify = TRUE)[,2]) %>%
  mutate(Diagnostic.1 = str_split(Contrast.1, pattern = " ", simplify = TRUE)[,1], ROI.1 = str_split(Contrast.1, pattern = " ", simplify = TRUE)[,2], Diagnostic.2 = str_split(Contrast.2, pattern = " ", simplify = TRUE)[,1], ROI.2 = str_split(Contrast.2, pattern = " ", simplify = TRUE)[,2]) %>%
  mutate(contrast = str_c(Diagnostic.1, Diagnostic.2 ,sep = "-"), contrast_ROI = str_c(ROI.1, ROI.2 ,sep = "-"))

coefs <- data.frame(coef(summary(m.1)))
coefs$p.z <- 2 * (1 - pnorm(abs(coefs$t.value)))
coefs

## Within regions comparison

TX_K_Within_regions <- ggplot(data = filter(pairs, ROI.1 == ROI.2), aes(
    x = contrast,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.4, nudge_y = 0.0003) +
  facet_wrap(ROI.1 ~.) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'K/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))

## Within diagnostics 

TX_K_Within_DIAG <- ggplot(data = filter(pairs, Diagnostic.1 == Diagnostic.2), aes(
    x = contrast_ROI,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.4, nudge_y = 0.0003) +
  facet_wrap(Diagnostic.1 ~.) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'K/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))

e <- effect("Age:Diagnostic:ROI", m.1)
e <- as.data.frame(e)

fit_K_lobes <- ggplot(e, aes(x = Age, y = fit,ymin=lower, ymax=upper, shape = Diagnostic)) + geom_pointrange() + geom_line() + theme_pubr() + labs(x = "Age [years]", y = "K", shape = "Diagnostic") + facet_wrap(. ~ ROI)

re <- as_tibble(ranef(m.1))

re <- filter(re, grpvar == "Sample:ROI") %>%
  mutate(ROI = str_sub(grp, -1, 20), K_shift = condval, Sample = str_split(grp, pattern = ":", simplify = TRUE)[,1], Diagnostic = str_split(grp, pattern = ":", simplify = TRUE)[,2], SD_K_shift = condsd) %>%
  dplyr::select(-c(condval, grpvar, term, condsd, grp))

ggplot(re, aes(y = K_shift, x = Sample)) +
  geom_point() +
  geom_errorbar(aes(ymin = K_shift+1.96*SD_K_shift, ymax = K_shift-1.96*SD_K_shift), width = 0.2) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  theme_pubr() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9)
  ) +
  labs(y ="K variation", x = "Sample") +
  facet_grid(ROI ~. )

```

### S \~ Age

```{r echo=FALSE}
m.1 <- lme4::lmer(S ~ Age * Diagnostic * ROI + (1|Sample) + (1|Sample:Diagnostic) + (1|Sample:ROI), data = data_lobes)

anova(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

mean <- lsmeans(m.1, ~ Diagnostic*ROI, var="Age")
m.lstk <- lstrends(m.1, ~ Diagnostic*ROI, var="Age")
pairs <- pairs(m.lstk) 

mean <- as_tibble(mean)
m.lstk <- as_tibble(m.lstk)

lst <- m.lstk %>% mutate(
    TX = paste(signif(Age.trend, 2), "±", signif(SE, 2)))

tableS <- full_join(mean, lst, by = c("Diagnostic", "ROI")) %>% mutate(percent = Age.trend*100/abs(lsmean), Variable = "S")

coefs <- data.frame(coef(summary(m.1)))
coefs$p.z <- 2 * (1 - pnorm(abs(coefs$t.value)))
coefs

pairs <- as_tibble(pairs) %>% mutate(Contrast.1 = str_split(contrast, pattern = " - ", simplify = TRUE)[,1], Contrast.2 = str_split(contrast, pattern = " - ", simplify = TRUE)[,2]) %>% mutate(Diagnostic.1 = str_split(Contrast.1, pattern = " ", simplify = TRUE)[,1], ROI.1 = str_split(Contrast.1, pattern = " ", simplify = TRUE)[,2], Diagnostic.2 = str_split(Contrast.2, pattern = " ", simplify = TRUE)[,1], ROI.2 = str_split(Contrast.2, pattern = " ", simplify = TRUE)[,2]) %>%
  mutate(contrast = str_c(Diagnostic.1, Diagnostic.2 ,sep = "-"), contrast_ROI = str_c(ROI.1, ROI.2 ,sep = "-"))

## Within regions comparion

TX_S_Within_regions <- ggplot(data = filter(pairs, ROI.1 == ROI.2), aes(
    x = contrast,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.4, nudge_y = 0.0003) +
  facet_wrap(ROI.1 ~.) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'S/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))

## Within diagnostics 

TX_S_Within_DIAG <- ggplot(data = filter(pairs, Diagnostic.1 == Diagnostic.2), aes(
    x = contrast_ROI,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.4, nudge_y = 0.0003) +
  facet_wrap(Diagnostic.1 ~.) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'S/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))

e <- effect("Age:Diagnostic:ROI", m.1)
e <- as.data.frame(e)

fit_S_lobes <- ggplot(e, aes(x = Age, y = fit,ymin=lower, ymax=upper, shape = Diagnostic)) + geom_pointrange() + geom_line() + theme_pubr() + labs(x = "Age [years]", y = "S", shape = "Diagnostic") + facet_wrap(. ~ ROI)

```

### I \~ Age

```{r echo=FALSE}
m.1 <- lme4::lmer(I ~ Age * Diagnostic * ROI + (1|Sample) + (1|Sample:Diagnostic) + (1|Sample:ROI), data = data_lobes)

anova(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

mean <- lsmeans(m.1, ~ Diagnostic*ROI, var="Age")
m.lstk <- lstrends(m.1, ~ Diagnostic*ROI, var="Age")
pairs <- pairs(m.lstk) 

mean <- as_tibble(mean)
m.lstk <- as_tibble(m.lstk)

lst <- m.lstk %>% mutate(
    TX = paste(signif(Age.trend, 2), "±", signif(SE, 2)))

tableI <- full_join(mean, lst, by = c("Diagnostic", "ROI")) %>% mutate(percent = Age.trend*100/abs(lsmean), Variable = "I")

coefs <- data.frame(coef(summary(m.1)))
coefs$p.z <- 2 * (1 - pnorm(abs(coefs$t.value)))
coefs

pairs <- as_tibble(pairs) %>% mutate(Contrast.1 = str_split(contrast, pattern = " - ", simplify = TRUE)[,1], Contrast.2 = str_split(contrast, pattern = " - ", simplify = TRUE)[,2]) %>% mutate(Diagnostic.1 = str_split(Contrast.1, pattern = " ", simplify = TRUE)[,1], ROI.1 = str_split(Contrast.1, pattern = " ", simplify = TRUE)[,2], Diagnostic.2 = str_split(Contrast.2, pattern = " ", simplify = TRUE)[,1], ROI.2 = str_split(Contrast.2, pattern = " ", simplify = TRUE)[,2]) %>%
  mutate(contrast = str_c(Diagnostic.1, Diagnostic.2 ,sep = "-"), contrast_ROI = str_c(ROI.1, ROI.2 ,sep = "-"))

## Within regions comparion

TX_I_Within_regions <- ggplot(data = filter(pairs, ROI.1 == ROI.2), aes(
    x = contrast,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.4, nudge_y = 0.0003) +
  facet_wrap(ROI.1 ~.) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'I/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))

## Within diagnostics 

TX_I_Within_DIAG <- ggplot(data = filter(pairs, Diagnostic.1 == Diagnostic.2), aes(
    x = contrast_ROI,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.4, nudge_y = 0.0003) +
  facet_wrap(Diagnostic.1 ~.) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'I/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))

e <- effect("Age:Diagnostic:ROI", m.1)
e <- as.data.frame(e)

fit_I_lobes <- ggplot(e, aes(x = Age, y = fit,ymin=lower, ymax=upper, shape = Diagnostic)) + geom_pointrange() + geom_line() + theme_pubr() + labs(x = "Age [years]", y = "I", shape = "Diagnostic") + facet_wrap(. ~ ROI)

```

```{r echo=FALSE}
tableT <- tableT %>% dplyr::select(c(Diagnostic, ROI, Age.trend, SE.y, percent, Variable))
tableK <- tableK %>% dplyr::select(c(Diagnostic, ROI, Age.trend, SE.y, percent, Variable))
tableS <- tableS %>% dplyr::select(c(Diagnostic, ROI, Age.trend, SE.y, percent, Variable))
tableI <- tableI %>% dplyr::select(c(Diagnostic, ROI, Age.trend, SE.y, percent, Variable))

rate <- full_join(tableT, tableK) %>% full_join(tableS) %>% full_join(tableI) %>% mutate(percent = signif(percent, 2), TX = paste(signif(Age.trend, 2), "±", signif(SE.y, 2)))

```

# Harmonization

```{r}
data_rate <-
  filter(data, Diagnostic == "CTL")

data_rate$Sample <-
  as.factor(data_rate$Sample)
data_rate$ROI <-
  factor(data_rate$ROI,
         levels = c("hemisphere", "F", "O", "P", "T"))

## AvgThickness ---
m.1 <-
  lme4::lmer(AvgThickness ~ Age * ROI + (1|Sample:ROI), data = data_rate)

re <- as_tibble(ranef(m.1)) %>%
  filter(grpvar == "Sample:ROI") %>%
  mutate(
    T_shift = condval,
    sd_T_shift = condsd,
    Sample = str_split(grp, pattern = ":", simplify = TRUE)[, 1],
    ROI = str_split(grp, pattern = ":", simplify = TRUE)[, 2]
  ) %>%
  dplyr::select(-c(condval, grpvar, term, condsd, grp))

Age.trend <- as_tibble(lstrends(m.1, ~ ROI, var = "Age")) %>%
  mutate(Age.trend_T = Age.trend) %>%
  dplyr::select(c(ROI, Age.trend_T))

data <- full_join(data, Age.trend) %>%
  full_join(re) %>%
  mutate(
    AvgThickness_shiftc = AvgThickness - T_shift,
    AvgThickness_age_decay = AvgThickness - Age.trend_T * (Age - Age.cor),
    AvgThickness_age_decay_shiftc = AvgThickness - T_shift - Age.trend_T *
      (Age - Age.cor),
    logAvgThickness_shiftc = log10(AvgThickness_shiftc),
    logAvgThickness_age_decay = log10(AvgThickness_age_decay),
    logAvgThickness_age_decay_shiftc = log10(AvgThickness_age_decay_shiftc)
  )

## TotalArea ---
m.1 <-
  lme4::lmer(TotalArea ~ Age * ROI + (1 | Sample:ROI), data = data_rate)

re <- as_tibble(ranef(m.1)) %>%
  filter(grpvar == "Sample:ROI") %>%
  mutate(
    AT_shift = condval,
    sd_AT_shift = condsd,
    Sample = str_split(grp, pattern = ":", simplify = TRUE)[, 1],
    ROI = str_split(grp, pattern = ":", simplify = TRUE)[, 2]
  ) %>%
  dplyr::select(-c(condval, grpvar, term, condsd, grp))

Age.trend <-
  as_tibble(lstrends(m.1, ~ ROI, var = "Age")) %>%
  mutate(Age.trend_AT = Age.trend) %>%
  dplyr::select(c(ROI, Age.trend_AT))

data <- full_join(data, re) %>%
  full_join(Age.trend) %>%
  mutate(
    TotalArea_shiftc = TotalArea - AT_shift,
    TotalArea_age_decay = TotalArea - Age.trend_AT * (Age - Age.cor),
    TotalArea_age_decay_shiftc = TotalArea - AT_shift - Age.trend_AT *
      (Age - Age.cor),
    logTotalArea_shiftc = log10(TotalArea_shiftc),
    logTotalArea_age_decay = log10(TotalArea_age_decay),
    logTotalArea_age_decay_shiftc = log10(TotalArea_age_decay_shiftc)
  )

## ExposedArea ---
m.1 <-
  lme4::lmer(
    ExposedArea  ~ Age * ROI + (1 | Sample:ROI), data = data_rate)

re <- as_tibble(ranef(m.1)) %>%
  filter(grpvar == "Sample:ROI") %>%
  mutate(
    AE_shift = condval,
    sd_AE_shift = condsd,
    Sample = str_split(grp, pattern = ":", simplify = TRUE)[, 1],
    ROI = str_split(grp, pattern = ":", simplify = TRUE)[, 2]
  ) %>%
  dplyr::select(-c(condval, grpvar, term, condsd, grp))

Age.trend <-
  as_tibble(lstrends(m.1, ~ ROI, var = "Age")) %>%
  mutate(Age.trend_AE = Age.trend) %>%
  dplyr::select(c(ROI, Age.trend_AE))

data <- full_join(data, re) %>%
  full_join(Age.trend) %>%
  mutate(
    ExposedArea_shiftc = ExposedArea - AE_shift,
    ExposedArea_age_decay = ExposedArea - Age.trend_AE * (Age - Age.cor),
    ExposedArea_age_decay_shiftc = ExposedArea - AE_shift - Age.trend_AE * (Age - Age.cor),
    logExposedArea_shiftc = log10(ExposedArea_shiftc),
    logExposedArea_age_decay = log10(ExposedArea_age_decay),
    logExposedArea_age_decay_shiftc = log10(ExposedArea_age_decay_shiftc)
  )

# ----
data <- data %>%
  mutate(
    localGI_age_decay = TotalArea_age_decay/ExposedArea_age_decay,
    localGI_shiftc = TotalArea_shiftc/ExposedArea_shiftc,
    localGI_age_decay_shiftc = TotalArea_age_decay_shiftc/ExposedArea_age_decay_shiftc,
    K_age_decay = log10(TotalArea_age_decay) + 1/4*log10(AvgThickness_age_decay^2) - 5/4*log10(ExposedArea_age_decay),
    K_shiftc = log10(TotalArea_shiftc) + 1/4*log10(AvgThickness_shiftc^2) - 5/4*log10(ExposedArea_shiftc),
    K_age_decay_shiftc = log10(TotalArea_age_decay_shiftc) + 1/4*log10(AvgThickness_age_decay_shiftc^2) - 5/4*log10(ExposedArea_age_decay_shiftc),
    I_age_decay = log10(TotalArea_age_decay) + log10(ExposedArea_age_decay) + log10(AvgThickness_age_decay^2),
    I_shiftc = log10(TotalArea_shiftc) + log10(ExposedArea_shiftc) + log10(AvgThickness_shiftc^2),
    I_age_decay_shiftc = log10(TotalArea_age_decay_shiftc) + log10(ExposedArea_age_decay_shiftc) + log10(AvgThickness_age_decay_shiftc^2),
    S_age_decay = 3/2*log10(TotalArea_age_decay) + 3/4*log10(ExposedArea_age_decay) - 9/4*log10(AvgThickness_age_decay^2),
    S_shiftc = 3/2*log10(TotalArea_shiftc) + 3/4*log10(ExposedArea_shiftc) - 9/4*log10(AvgThickness_shiftc^2),
    S_age_decay_shiftc = 3/2*log10(TotalArea_age_decay_shiftc) + 3/4*log10(ExposedArea_age_decay_shiftc) - 9/4*log10(AvgThickness_age_decay_shiftc^2),
    Knorm_shiftc = K_shiftc / sqrt(1 + (1 / 4) ^ 2 + (5 / 2) ^ 2),
    Snorm_shiftc = S_shiftc / sqrt((3 / 2) ^ 2 + (3 / 4) ^ 2 + (9 / 4) ^ 2),
    Inorm_shiftc = I_shiftc / sqrt(1 ^ 2 + 1 ^ 2 + 1 ^ 2),
    Knorm_age_decay = K_age_decay / sqrt(1 + (1 / 4) ^ 2 + (5 / 2) ^ 2),
    Snorm_age_decay = S_age_decay / sqrt((3 / 2) ^ 2 + (3 / 4) ^ 2 + (9 / 4) ^ 2),
    Inorm_age_decay = I_age_decay / sqrt(1 ^ 2 + 1 ^ 2 + 1 ^ 2),
    Knorm_age_decay_shiftc = K_age_decay_shiftc / sqrt(1 + (1 / 4) ^ 2 + (5 / 2) ^ 2),
    Snorm_age_decay_shiftc = S_age_decay_shiftc / sqrt((3 / 2) ^ 2 +  (3 / 4) ^ 2 + (9 / 4) ^ 2),
    Inorm_age_decay_shiftc = I_age_decay_shiftc / sqrt(1 ^ 2 + 1 ^ 2 + 1 ^ 2)
  )

```

# Harmonization figures
```{r include=FALSE}
GI_shifta_lobes <- ggplot(filter(data, ROI != "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = localGI, color = Sample))+
  geom_point() +
  theme_pubr() + labs(y = "GI") +
  facet_grid(ROI ~ .)

GI_shiftb_lobes <- ggplot(filter(data, ROI != "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = localGI_shiftc, color = Sample))+
  geom_point() +
  theme_pubr() + labs(y = "GI (harmonized)") +
  facet_grid(ROI ~ .)

GI_shift_lobes <- ggarrange(GI_shifta_lobes, GI_shiftb_lobes,labels = c("A","B"), nrow = 2, ncol = 1, font.label = list(size = 11), common.legend = TRUE, legend = "top")
GI_shift_lobes

```

```{r echo=FALSE}
K_shifta_lobes <- ggplot(filter(data, ROI != "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = K, color = Sample, alpha = 0.4))+
  geom_point() +
  theme_pubr() + 
  guides(alpha = "none") +
  facet_grid(ROI ~ .)

K_shiftb_lobes <- ggplot(filter(data, ROI != "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = K_shiftc, color = Sample, alpha = 0.4))+
  geom_point() +
    guides(alpha = "none") + 
  theme_pubr() + labs(y = "K (harmonized)") +
  facet_grid(ROI ~ .)

K_shift_lobes <- ggarrange(K_shifta_lobes, K_shiftb_lobes,labels = c("A","B"), nrow = 2, ncol = 1, font.label = list(size = 11), common.legend = TRUE, legend = "top")
K_shift_lobes

```

```{r echo=FALSE}
S_shifta_lobes <- ggplot(filter(data, ROI != "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = S, color = Sample))+
  geom_point() +
  theme_pubr() +
  facet_grid(ROI ~ .)

S_shiftb_lobes <- ggplot(filter(data, ROI != "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = S_shiftc, color = Sample))+
  geom_point() +
  theme_pubr() + labs(y = "S (harmonized)") +
  facet_grid(ROI ~ .)

S_shift_lobes <- ggarrange(S_shifta_lobes, S_shiftb_lobes,labels = c("A","B"), nrow = 2, ncol = 1, font.label = list(size = 11), common.legend = TRUE, legend = "top")
S_shift_lobes

```

```{r echo=FALSE}
I_shifta_lobes <- ggplot(filter(data, ROI != "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = I, color = Sample))+
  geom_point() +
  theme_pubr() +
  facet_grid(ROI ~ .)

I_shiftb_lobes <- ggplot(filter(data, ROI != "hemisphere", Diagnostic == "CTL"), aes(x = Age, y = I_shiftc, color = Sample))+
  geom_point() +
  theme_pubr() + labs(y = "I (harmonized)") +
  facet_grid(ROI ~ .)

I_shift_lobes <- ggarrange(I_shifta_lobes, I_shiftb_lobes,labels = c("A","B"), nrow = 2, ncol = 1, font.label = list(size = 11), common.legend = TRUE, legend = "top")
I_shift_lobes

```

```{r echo=FALSE}
data_lobes <- filter(data, ROI != "hemisphere", Diagnostic == "CTL" | Diagnostic == "MCI"| Diagnostic == "AD")
data_lobes$Diagnostic <- factor(data_lobes$Diagnostic, levels = c("CTL", "MCI","AD"))
data_lobes$Sample <- as.factor(data_lobes$Sample)

```

# After harmonization

## AvgThickness \~ Age
```{r echo=FALSE}
m.1 <- lme4::lmer(AvgThickness_shiftc ~ Age * Diagnostic * ROI + (1|Sample) + (1|Sample:Diagnostic)+(1|Sample:ROI), data = data_lobes)

anova(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

mean <- lsmeans(m.1, ~ Diagnostic*ROI, var="Age")
m.lstk <- lstrends(m.1, ~ Diagnostic*ROI, var="Age")
pairs <- pairs(m.lstk) 

mean <- as_tibble(mean)
m.lstk <- as_tibble(m.lstk)

lst <- m.lstk %>% mutate(
    TX = paste(signif(Age.trend, 2), "±", signif(SE, 2)))

tableT <- full_join(mean, lst, by = c("Diagnostic", "ROI")) %>% mutate(percent = Age.trend*100/abs(lsmean), Variable = "T_shiftc")

pairs <- as_tibble(pairs) %>%
  mutate(Contrast.1 = str_split(contrast, pattern = " - ", simplify = TRUE)[,1], Contrast.2 = str_split(contrast, pattern = " - ", simplify = TRUE)[,2]) %>%
  mutate(Diagnostic.1 = str_split(Contrast.1, pattern = " ", simplify = TRUE)[,1], ROI.1 = str_split(Contrast.1, pattern = " ", simplify = TRUE)[,2], Diagnostic.2 = str_split(Contrast.2, pattern = " ", simplify = TRUE)[,1], ROI.2 = str_split(Contrast.2, pattern = " ", simplify = TRUE)[,2]) %>%
  mutate(contrast = str_c(Diagnostic.1, Diagnostic.2 ,sep = "-"), contrast_ROI = str_c(ROI.1, ROI.2 ,sep = "-"))

coefs <- data.frame(coef(summary(m.1)))
coefs$p.z <- 2 * (1 - pnorm(abs(coefs$t.value)))
coefs

## Within regions comparison

ggplot(data = filter(pairs, ROI.1 == ROI.2), aes(
    x = contrast,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.4, nudge_y = 0.0003) +
  facet_wrap(ROI.1 ~.) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'AvgThickness/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme( axis.text.x = element_text(angle = 45, hjust = 1, size=9))

## Within diagnostics 

ggplot(data = filter(pairs, Diagnostic.1 == Diagnostic.2), aes(
    x = contrast_ROI,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.4, nudge_y = 0.0003) +
  facet_wrap(Diagnostic.1 ~.) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'AvgThickness/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))

e <- effect("Age:Diagnostic:ROI", m.1)
e <- as.data.frame(e)

ggplot(e, aes(x = Age, y = fit,ymin=lower, ymax=upper, shape = Diagnostic)) + geom_pointrange() + geom_line() + theme_pubr() + labs(x = "Age [years]", y = "AvgThickness", shape = "Diagnostic") + facet_wrap(. ~ ROI)

```


## GI \~ Age
```{r echo=FALSE}
m.1 <- lme4::lmer(localGI_shiftc ~ Age * Diagnostic * ROI + (1|Sample) + (1|Sample:Diagnostic)+(1|Sample:ROI), data = data_lobes)

anova(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

mean <- lsmeans(m.1, ~ Diagnostic*ROI, var="Age")
m.lstk <- lstrends(m.1, ~ Diagnostic*ROI, var="Age")
pairs <- pairs(m.lstk) 

mean <- as_tibble(mean)
m.lstk <- as_tibble(m.lstk)

lst <- m.lstk %>% mutate(
    TX = paste(signif(Age.trend, 2), "±", signif(SE, 2)))

tableGI <- full_join(mean, lst, by = c("Diagnostic", "ROI")) %>% mutate(percent = Age.trend*100/abs(lsmean), Variable = "localGI_shiftc")

pairs <- as_tibble(pairs) %>%
  mutate(Contrast.1 = str_split(contrast, pattern = " - ", simplify = TRUE)[,1], Contrast.2 = str_split(contrast, pattern = " - ", simplify = TRUE)[,2]) %>%
  mutate(Diagnostic.1 = str_split(Contrast.1, pattern = " ", simplify = TRUE)[,1], ROI.1 = str_split(Contrast.1, pattern = " ", simplify = TRUE)[,2], Diagnostic.2 = str_split(Contrast.2, pattern = " ", simplify = TRUE)[,1], ROI.2 = str_split(Contrast.2, pattern = " ", simplify = TRUE)[,2]) %>%
  mutate(contrast = str_c(Diagnostic.1, Diagnostic.2 ,sep = "-"), contrast_ROI = str_c(ROI.1, ROI.2 ,sep = "-"))

coefs <- data.frame(coef(summary(m.1)))
coefs$p.z <- 2 * (1 - pnorm(abs(coefs$t.value)))
coefs

## Within regions comparison

ggplot(data = filter(pairs, ROI.1 == ROI.2), aes(
    x = contrast,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.4, nudge_y = 0.0003) +
  facet_wrap(ROI.1 ~.) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'GI/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))

## Within diagnostics 

ggplot(data = filter(pairs, Diagnostic.1 == Diagnostic.2), aes(
    x = contrast_ROI,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.4, nudge_y = 0.0003) +
  facet_wrap(Diagnostic.1 ~.) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'GI/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))

e <- effect("Age:Diagnostic:ROI", m.1)
e <- as.data.frame(e)

ggplot(e, aes(x = Age, y = fit,ymin=lower, ymax=upper, shape = Diagnostic)) + geom_pointrange() + geom_line() + theme_pubr() + labs(x = "Age [years]", y = "GI", shape = "Diagnostic") + facet_wrap(. ~ ROI) 

```

## K \~ Age
```{r echo=FALSE}
m.1 <- lme4::lmer(K_shiftc ~ Age * Diagnostic * ROI + (1|Sample) + (1|Sample:Diagnostic) + (1|Sample:ROI), data = data_lobes)

anova(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

mean <- lsmeans(m.1, ~ Diagnostic*ROI, var="Age")
m.lstk <- lstrends(m.1, ~ Diagnostic*ROI, var="Age")
pairs <- pairs(m.lstk) 

mean <- as_tibble(mean)
m.lstk <- as_tibble(m.lstk)

lst <- m.lstk %>% mutate(
    TX = paste(signif(Age.trend, 2), "±", signif(SE, 2)))

tableK <- full_join(mean, lst, by = c("Diagnostic", "ROI")) %>% mutate(percent = Age.trend*100/abs(lsmean), Variable = "K_shiftc")

pairs <- as_tibble(pairs) %>%
  mutate(Contrast.1 = str_split(contrast, pattern = " - ", simplify = TRUE)[,1], Contrast.2 = str_split(contrast, pattern = " - ", simplify = TRUE)[,2]) %>%
  mutate(Diagnostic.1 = str_split(Contrast.1, pattern = " ", simplify = TRUE)[,1], ROI.1 = str_split(Contrast.1, pattern = " ", simplify = TRUE)[,2], Diagnostic.2 = str_split(Contrast.2, pattern = " ", simplify = TRUE)[,1], ROI.2 = str_split(Contrast.2, pattern = " ", simplify = TRUE)[,2]) %>%
  mutate(contrast = str_c(Diagnostic.1, Diagnostic.2 ,sep = "-"), contrast_ROI = str_c(ROI.1, ROI.2 ,sep = "-"))

coefs <- data.frame(coef(summary(m.1)))
coefs$p.z <- 2 * (1 - pnorm(abs(coefs$t.value)))
coefs

## Within regions comparison

TX_K_Within_regions <- ggplot(data = filter(pairs, ROI.1 == ROI.2), aes(
    x = contrast,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.4, nudge_y = 0.0003) +
  facet_wrap(ROI.1 ~.) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'K/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))
TX_K_Within_regions

## Within diagnostics 

ggplot(data = filter(pairs, Diagnostic.1 == Diagnostic.2), aes(
    x = contrast_ROI,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.4, nudge_y = 0.0003) +
  facet_wrap(Diagnostic.1 ~.) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'K/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))

e <- effect("Age:Diagnostic:ROI", m.1)
e <- as.data.frame(e)

fit_K_lobes <- ggplot(e, aes(x = Age, y = fit,ymin=lower, ymax=upper, shape = Diagnostic)) + geom_pointrange() + geom_line() + theme_pubr() + labs(x = "Age [years]", y = "K", shape = "Diagnostic") + facet_wrap(. ~ ROI)
fit_K_lobes

```

## S \~ Age

```{r echo=FALSE}
m.1 <- lme4::lmer(S_shiftc ~ Age * Diagnostic * ROI + (1|Sample) + (1|Sample:Diagnostic) + (1|Sample:ROI), data = data_lobes)

anova(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

mean <- lsmeans(m.1, ~ Diagnostic*ROI, var="Age")
m.lstk <- lstrends(m.1, ~ Diagnostic*ROI, var="Age")
pairs <- pairs(m.lstk) 

mean <- as_tibble(mean)
m.lstk <- as_tibble(m.lstk)

lst <- m.lstk %>% mutate(
    TX = paste(signif(Age.trend, 2), "±", signif(SE, 2)))

tableS <- full_join(mean, lst, by = c("Diagnostic", "ROI")) %>% mutate(percent = Age.trend*100/abs(lsmean), Variable = "S_shiftc")

coefs <- data.frame(coef(summary(m.1)))
coefs$p.z <- 2 * (1 - pnorm(abs(coefs$t.value)))
coefs

pairs <- as_tibble(pairs) %>% mutate(Contrast.1 = str_split(contrast, pattern = " - ", simplify = TRUE)[,1], Contrast.2 = str_split(contrast, pattern = " - ", simplify = TRUE)[,2]) %>% mutate(Diagnostic.1 = str_split(Contrast.1, pattern = " ", simplify = TRUE)[,1], ROI.1 = str_split(Contrast.1, pattern = " ", simplify = TRUE)[,2], Diagnostic.2 = str_split(Contrast.2, pattern = " ", simplify = TRUE)[,1], ROI.2 = str_split(Contrast.2, pattern = " ", simplify = TRUE)[,2]) %>%
  mutate(contrast = str_c(Diagnostic.1, Diagnostic.2 ,sep = "-"), contrast_ROI = str_c(ROI.1, ROI.2 ,sep = "-"))

## Within regions comparion

TX_S_Within_regions <- ggplot(data = filter(pairs, ROI.1 == ROI.2), aes(
    x = contrast,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.4, nudge_y = 0.0003) +
  facet_wrap(ROI.1 ~.) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'S/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))
TX_S_Within_regions

## Within diagnostics 

ggplot(data = filter(pairs, Diagnostic.1 == Diagnostic.2), aes(
    x = contrast_ROI,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.4, nudge_y = 0.0003) +
  facet_wrap(Diagnostic.1 ~.) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'S/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))

e <- effect("Age:Diagnostic:ROI", m.1)
e <- as.data.frame(e)

fit_S_lobes <- ggplot(e, aes(x = Age, y = fit,ymin=lower, ymax=upper, shape = Diagnostic)) + geom_pointrange() + geom_line() + theme_pubr() + labs(x = "Age [years]", y = "S", shape = "Diagnostic") + facet_wrap(. ~ ROI)
fit_S_lobes

```

## I \~ Age

```{r echo=FALSE}
m.1 <- lme4::lmer(I_shiftc ~ Age * Diagnostic * ROI + (1|Sample) + (1|Sample:Diagnostic) + (1|Sample:ROI), data = data_lobes)

anova(m.1)
sigma.hat(m.1)
r.squaredGLMM(m.1)

mean <- lsmeans(m.1, ~ Diagnostic*ROI, var="Age")
m.lstk <- lstrends(m.1, ~ Diagnostic*ROI, var="Age")
pairs <- pairs(m.lstk) 

mean <- as_tibble(mean)
m.lstk <- as_tibble(m.lstk)

lst <- m.lstk %>% mutate(
    TX = paste(signif(Age.trend, 2), "±", signif(SE, 2)))

tableI <- full_join(mean, lst, by = c("Diagnostic", "ROI")) %>% mutate(percent = Age.trend*100/abs(lsmean), Variable = "I_shiftc")

coefs <- data.frame(coef(summary(m.1)))
coefs$p.z <- 2 * (1 - pnorm(abs(coefs$t.value)))
coefs

pairs <- as_tibble(pairs) %>% mutate(Contrast.1 = str_split(contrast, pattern = " - ", simplify = TRUE)[,1], Contrast.2 = str_split(contrast, pattern = " - ", simplify = TRUE)[,2]) %>% mutate(Diagnostic.1 = str_split(Contrast.1, pattern = " ", simplify = TRUE)[,1], ROI.1 = str_split(Contrast.1, pattern = " ", simplify = TRUE)[,2], Diagnostic.2 = str_split(Contrast.2, pattern = " ", simplify = TRUE)[,1], ROI.2 = str_split(Contrast.2, pattern = " ", simplify = TRUE)[,2]) %>%
  mutate(contrast = str_c(Diagnostic.1, Diagnostic.2 ,sep = "-"), contrast_ROI = str_c(ROI.1, ROI.2 ,sep = "-"))

## Within regions comparion

TX_I_Within_regions <- ggplot(data = filter(pairs, ROI.1 == ROI.2), aes(
    x = contrast,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.4, nudge_y = 0.0003) +
  facet_wrap(ROI.1 ~.) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'I/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))
TX_I_Within_regions

## Within diagnostics 

ggplot(data = filter(pairs, Diagnostic.1 == Diagnostic.2), aes(
    x = contrast_ROI,
    y = estimate,
    ymin = estimate - SE,
    ymax = estimate + SE)) +
    geom_hline(yintercept = 0,
               linetype = "11",
               colour = "grey60") +
    geom_pointrange( position = position_dodge(width = 0.2)) +
   geom_text(aes(label = str_c("p adj ", signif(p.value, digits = 2))), nudge_x = 0.4, nudge_y = 0.0003) +
  facet_wrap(Diagnostic.1 ~.) +
    coord_flip() + 
    labs(y =  expression('Differences in slopes ('*Delta*'I/'*Delta*'Age)'), x = "Contrast") +
  theme_pubr() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=9))

e <- effect("Age:Diagnostic:ROI", m.1)
e <- as.data.frame(e)

fit_I_lobes <- ggplot(e, aes(x = Age, y = fit,ymin=lower, ymax=upper, shape = Diagnostic)) + geom_pointrange() + geom_line() + theme_pubr() + labs(x = "Age [years]", y = "I", shape = "Diagnostic") + facet_wrap(. ~ ROI) 
fit_I_lobes

```

```{r echo=FALSE}
tableT <- tableT %>% dplyr::select(c(Diagnostic, ROI, Age.trend, SE.y, percent, Variable))
tableK <- tableK %>% dplyr::select(c(Diagnostic, ROI, Age.trend, SE.y, percent, Variable))
tableS <- tableS %>% dplyr::select(c(Diagnostic, ROI, Age.trend, SE.y, percent, Variable))
tableI <- tableI %>% dplyr::select(c(Diagnostic, ROI, Age.trend, SE.y, percent, Variable))
tableGI <- tableGI %>% dplyr::select(c(Diagnostic, ROI, Age.trend, SE.y, percent, Variable))

rate <- full_join(tableT, tableK) %>%
  full_join(tableS) %>%
  full_join(tableI) %>%
  full_join(tableGI) %>%
  mutate(TX = paste(signif(Age.trend, 2), "±", signif(SE.y, 2)), percent = signif(percent, 2)) %>%
  dplyr::select(-c(Age.trend, SE.y)) %>%
  kable() %>%
  kable_styling()

```

## Figures

```{r echo=FALSE}

fig_TX_age_lobes_ROI <- ggarrange(TX_K_Within_regions, TX_S_Within_regions, TX_I_Within_regions,labels = c("A","B","C"), nrow = 3, ncol = 1, font.label = list(size = 11), common.legend = TRUE, legend = "top")

fig_TX_age_lobes_DIAG <- ggarrange(TX_K_Within_DIAG, TX_S_Within_DIAG, TX_I_Within_DIAG,labels = c("A","B","C"), nrow = 3, ncol = 1, font.label = list(size = 11), common.legend = TRUE, legend = "top")

fig_TX_age_lobes_ROI
fig_TX_age_lobes_DIAG

fit_lobes <- ggarrange(fit_K_lobes, ggarrange(fit_S_lobes, fit_I_lobes,labels = c("B","C"), nrow = 1, ncol = 2, font.label = list(size = 11)),labels = c("A"), nrow = 2, ncol = 1, font.label = list(size = 11), common.legend = TRUE, legend = "top")

fit_S_lobes

```
